name: meta-micropython

on:
  push:
    branches:
      - master
      - master-next
  pull_request:

jobs:
  build-and-test:
    runs-on: [self-hosted, linux]
    container:
      image: dynamicdevices/yocto-ci-build:latest
      options: --privileged -v /dev/net/tun:/dev/net/tun -v /dev/kvm:/dev/kvm
    strategy:
      matrix:
        branch: [master]
        arch: [x86, arm]
    env:
      name: build-and-test
      ARCH: ${{ matrix.arch }}
      BRANCH: ${{ matrix.branch }}
    steps:
    - name: Checkout meta-micropython
      uses: actions/checkout@v2
      with:
        clean: false
        path: ${{ matrix.branch }}/meta-micropython
    - name: Update repo poky
      run: |
        if [ ! -d ${BRANCH}/poky ]; then
          git clone git://git.yoctoproject.org/poky -b ${BRANCH} ${BRANCH}/poky
        else
          cd ${BRANCH}/poky
          git pull origin ${BRANCH}
          cd ../..
        fi
    - name: Update repo meta-openembedded
      run: |
        if [ ! -d ${BRANCH}/meta-openembedded ]; then
          git clone https://github.com/openembedded/meta-openembedded.git -b ${BRANCH} ${BRANCH}/meta-openembedded
        else
          cd ${BRANCH}/meta-openembedded
          git pull origin ${BRANCH}
          cd ../..
        fi 
    - name: Configuring
      run: |
        . ./${BRANCH}/poky/oe-init-build-env ${BRANCH}/build
        if [[ ! $(grep meta-micropython/meta-micropython/${BRANCH}/meta-micropython conf/bblayers.conf) ]]; then
          echo "BBLAYERS += '$GITHUB_WORKSPACE/${BRANCH}/meta-micropython'" >> conf/bblayers.conf
        fi
        if [[ ! $(grep meta-openembedded conf/bblayers.conf) ]]; then
          echo "BBLAYERS += '$GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-oe'" >> conf/bblayers.conf
        fi
        if [[ ! $(grep rm_work conf/local.conf) ]]; then
          echo "INHERIT += ' rm_work '" >> conf/local.conf
        fi
        if [[ ! $(grep '#Make test image' conf/local.conf) ]]; then
          echo "#Make test image" >> conf/local.conf
          echo "INHERIT += ' testimage '" >> conf/local.conf
        fi
    - name: Building
      run: |
        . ./${BRANCH}/poky/oe-init-build-env ${BRANCH}/build

        export BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE} MACHINE DL_DIR"

        env MACHINE="qemu${ARCH}" DL_DIR="$GITHUB_WORKSPACE/downloads" bitbake -k core-image-minimal
    - name: Testing
      run: |
        . ./${BRANCH}/poky/oe-init-build-env ${BRANCH}/build

        export BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE} MACHINE DL_DIR"
        export TERM=linux
        env MACHINE="qemu${ARCH}" DL_DIR="$GITHUB_WORKSPACE/downloads" bitbake core-image-minimal -c testimage
